export const credits = [
  '>LIST PERSONNEL',
  ' ',
  ' ',
  'Gautam Babbar',
  'Ted Backman',
  'Kelly Bailey',
  'Jeff Ballinger',
  'Aaron Barber',
  'Jeep Barnett',
  'Jeremy Bennett',
  'Dan Berger',
  'Yahn Bernier',
  'Ken Birdwell',
  'Derrick Birum',
  'Mike Blaszczak',
  'Iestyn Bleasdale-Shepherd',
  'Chris Bokitch',
  'Steve Bond',
  'Matt Boone',
  'Antoine Bourdon',
  'Jamaal Bradley',
  'Jason Brashill',
  'Charlie Brown',
  'Charlie Burgin',
  'Andrew Burke',
  'Augusta Butlin',
  'Julie Caldwell',
  'Dario Casali',
  'Chris Chin',
  'Jess Cliffe',
  'Phil Co',
  'John Cook',
  'Christen Coomer',
  'Greg Coomer',
  'Scott Dalton',
  'Kerry Davis',
  'Jason Deakins',
  'Joe Demers',
  'Ariel Diaz',
  'Quintin Doroquez',
  'Jim Dose',
  'Chris Douglass',
  'Laura Dubuk',
  'Mike Dunkle',
  'Mike Durand',
  'Mike Dussault',
  'Dhabih Eng',
  'Katie Engel',
  'Chet Faliszek',
  'Adrian Finol',
  'Bill Fletcher',
  'Moby Francke',
  'Stephane Gaudette',
  'Kathy Gehrig',
  'Vitaliy Genkin',
  'Paul Graham',
  'Chris Green',
  'Chris Grinstead',
  'John Guthrie',
  'Aaron Halifax',
  'Reagan Halifax',
  'Leslie Hall',
  'Jeff Hameluck',
  'Joe Han',
  'Don Holden',
  'Jason Holtman',
  'Gray Horsfield',
  'Keith Huggins',
  'Jim Hughes',
  'Jon Huisingh',
  'Brian Jacobson',
  'Lars Jensvold',
  'Erik Johnson',
  'Jakob Jungels',
  'Rich Kaethler',
  'Steve Kalning',
  'Aaron Kearly',
  'Iikka Keranen',
  'David Kircher',
  'Eric Kirchmer',
  'Scott Klintworth',
  'Alden Kroll',
  'Marc Laidlaw',
  'Jeff Lane',
  'Tim Larkin',
  'Dan LeFree',
  'Isabelle LeMay',
  'Tom Leonard',
  'Jeff Lind',
  'Doug Lombardi',
  'Bianca Loomis',
  'Richard Lord',
  'Realm Lovejoy',
  'Randy Lundeen',
  'Scott Lynch',
  'Ido Magal',
  'Nick Maggiore',
  'John McCaskey',
  'Patrick McClard',
  'Steve McClure',
  'Hamish McKenzie',
  'Gary McTaggart',
  'Jason Mitchell',
  'Mike Morasky',
  'John Morello II',
  'Bryn Moslow',
  'Arsenio Navarro',
  'Gabe Newell',
  'Milton Ngan',
  'Jake Nicholson',
  'Martin Otten',
  'Nick Papineau',
  'Karen Prell',
  'Bay Raitt',
  'Tristan Reidford',
  'Alfred Reynolds',
  'Matt Rhoten',
  'Garret Rickey',
  'Dave Riller',
  'Elan Ruskin',
  'Matthew Russell',
  'Jason Ruymen',
  'David Sawyer',
  'Marc Scaparro',
  'Wade Schin',
  'Matthew Scott',
  'Aaron Seeler',
  'Jennifer Seeley',
  'Taylor Sherman',
  'Eric Smith',
  'Jeff Sorensen',
  'David Speyrer',
  'Jay Stelly',
  'Jeremy Stone',
  'Eric Strand',
  'Kim Swift',
  'Kelly Thornton',
  'Eric Twelker',
  'Carl Uhlman',
  'Doug Valente',
  'Bill Van Buren',
  'Gabe Van Engel',
  'Alex Vlachos',
  'Robin Walker',
  'Joshua Weier',
  'Andrea Wicklund',
  'Greg Winkler',
  'Erik Wolpaw',
  'Doug Wood',
  'Matt T. Wood',
  'Danika Wright',
  'Matt Wright',
  'Shawn Zabecki',
  'Torsten Zabka ',
  ' ',
  ' ',
  ' ',
  ' ',
  "'Still Alive' by:",
  'Jonathan Coulton',
  ' ',
  ' ',
  ' ',
  'Voices:',
  'Ellen McLain - GlaDOS, Turrets',
  'Mike Patton - THE ANGER SPHERE',
  ' ',
  ' ',
  ' ',
  'Voice Casting:',
  'Shana LandsburgTeri Fiddleman',
  ' ',
  ' ',
  ' ',
  ' ',
  'Voice Recording:',
  'Pure Audio, Seattle, WA',
  ' ',
  ' ',
  ' ',
  ' ',
  'Voice recording',
  'scheduling and logistics:',
  'Pat Cockburn, Pure Audio',
  ' ',
  ' ',
  ' ',
  ' ',
  'Translations:',
  'SDL',
  ' ',
  ' ',
  ' ',
  ' ',
  'Crack Legal Team:',
  'Liam Lavery',
  'Karl Quackenbush',
  'Kristen Boraas',
  'Kevin Rosenfield',
  'Alan Bruggeman',
  'Dennis Tessier',
  ' ',
  ' ',
  ' ',
  'Thanks for the use of their face:',
  'Alesia Glidewell - Chell',
  ' ',
  ' ',
  ' ',
  'Special thanks to everyone at:',
  'Alienware',
  'ATI',
  'Dell',
  'Falcon Northwest',
  'Havok',
  'SOFTIMAGE',
  'and Don Kemmis, SLK Technologies',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  'THANK YOU FOR PARTICIPATING',
  'IN THIS',
  'ENRICHMENT CENTER ACTIVITY!!',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
];
