export interface Lyric {
  asciiArt?: number;
  sameLine?: boolean;
  duration: number;
  line: string;
}

export const lyrics: Lyric[] = [
  { duration: 2000, line: "Forms FORM-29827281-12:" },
  { duration: 2000, line: "Test Assessment Report" },
  { duration: 10, line: "^" },
  { duration: 10, line: "^" },
  { duration: 2850, line: " " },
  { duration: 2050, line: "This was a triumph." },
  { duration: 1900, line: " " },
  { duration: 2100, line: "I'm making a note here:" },
  { duration: 100, line: " " },
  { duration: 1800, line: "HUGE SUCCESS." },
  { duration: 1000, line: " " },
  { duration: 2360, line: "It's hard to overstate" },
  { duration: 40, line: " " },
  { duration: 2710, line: "my satisfaction." },
  { duration: 2130, line: " " },
  { asciiArt: 0, duration: 1760, line: "Aperture Science" },
  { duration: 2100, line: " " },
  { duration: 1570, line: "We do what we must" },
  { duration: 200, line: " " },
  { duration: 750, line: "because", sameLine: true },
  { duration: 100, line: "* " },
  { duration: 710, line: "we can." },
  { duration: 1670, line: " " },
  { duration: 1550, line: "For the good", sameLine: true },
  { duration: 1530, line: " of all of us." },
  { duration: 279, line: " " },
  { asciiArt: 5, duration: 1741, line: "Except the ones who are dead." },
  { duration: 400, line: "^" },
  { asciiArt: 0, duration: 1858, line: "But there's no sense crying" },
  { duration: 10, line: " " },
  { duration: 1782, line: "over every mistake." },
  { duration: 200, line: " " },
  { duration: 1985, line: "You just keep on trying" },
  { duration: 10, line: " " },
  { duration: 1366, line: "till you run out of", sameLine: true },
  { duration: 400, line: " cake." },
  { duration: 186, line: " " },
  { asciiArt: 4, duration: 1970, line: "And the Science gets done." },
  { duration: 1970, line: "And you make a neat gun." },
  { duration: 20, line: " " },
  { asciiArt: 0, duration: 1520, line: "For the people who are" },
  { duration: 20, line: " " },
  { duration: 1500, line: "still alive." },
  { duration: 1500, line: " " },
  { duration: 100, line: "&" },
  { duration: 550, line: "Forms FORM-55551-5:" },
  { duration: 1100, line: "Personnel File Addendum:" },
  { duration: 660, line: "^" },
  { duration: 2350, line: "Dear <<Subject Name Here>>," },
  { duration: 60, line: "^" },
  { duration: 1917, line: "I'm not even angry." },
  { duration: 2368, line: " " },
  { duration: 697, line: "I'm being ", sameLine: true },
  { duration: 650, line: "so", sameLine: true },
  { duration: 906, line: " sincere ", sameLine: true },
  { duration: 1115, line: "right now." },
  { duration: 1625, line: " " },
  { duration: 650, line: "Even ", sameLine: true },
  { duration: 1347, line: "though you ", sameLine: true },
  { asciiArt: 7, duration: 488, line: "broke ", sameLine: true },
  { duration: 998, line: "my heart." },
  { duration: 325, line: "And ", sameLine: true },
  { duration: 488, line: "killed ", sameLine: true },
  { duration: 557, line: "me." },
  { duration: 2000, line: " " },
  { asciiArt: 2, duration: 1649, line: "And tore me to pieces." },
  { duration: 2322, line: " " },
  { duration: 1440, line: "And threw every piece", sameLine: true },
  { duration: 302, line: "* " },
  { duration: 580, line: "into", sameLine: true },
  { duration: 395, line: "* " },
  { asciiArt: 10, duration: 882, line: "a fire." },
  { duration: 1649, line: " " },
  { duration: 1400, line: "As they burned ", sameLine: true },
  { duration: 1509, line: "it hurt because" },
  { duration: 325, line: " " },
  { asciiArt: 8, duration: 1625, line: "I was so happy for you!" },
  { duration: 441, line: " " },
  { duration: 2067, line: "Now these points of data" },
  { duration: 1950, line: "make a beautiful line." },
  { duration: 2020, line: "And we're out of beta." },
  { duration: 1950, line: "We're releasing on time." },
  { asciiArt: 2, duration: 2113, line: "So I'm GLaD. I got burned." },
  { asciiArt: 4, duration: 2020, line: "Think of all the things we learned" },
  { asciiArt: 0, duration: 1556, line: "for the people who are" },
  { duration: 395, line: "still", sameLine: true },
  { duration: 1440, line: " alive." },
  { duration: 1500, line: " " },
  { duration: 100, line: "&" },
  { duration: 450, line: "Forms FORM-55551-6:" },
  { duration: 1310, line: "Personnel File Addendum Addendum:" },
  { duration: 660, line: "^" },
  { duration: 2200, line: "One last thing:" },
  { duration: 50, line: "^" },
  { duration: 1324, line: "Go ahead and leave ", sameLine: true },
  { duration: 627, line: "me." },
  { duration: 1788, line: " " },
  { duration: 534, line: "I think ", sameLine: true },
  { duration: 1184, line: "I prefer ", sameLine: true },
  { duration: 1022, line: "to stay ", sameLine: true },
  { duration: 232, line: "in", sameLine: true },
  { duration: 882, line: "side." },
  { duration: 1430, line: " " },
  { duration: 511, line: "May", sameLine: true },
  { duration: 2972, line: "be you'll find someone else" },
  { duration: 1254, line: "to help you." },
  { duration: 2252, line: " " },
  { duration: 511, line: "Maybe ", sameLine: true },
  { asciiArt: 6, duration: 325, line: "Black ", sameLine: true },
  { duration: 998, line: "Mesa", sameLine: true },
  { duration: 2183, line: "... " },
  { duration: 1440, line: "THAT WAS A JOKE.", sameLine: true },
  { duration: 1021, line: "* " },
  { duration: 279, line: "FAT ", sameLine: true },
  { duration: 859, line: "CHANCE." },
  { duration: 1393, line: " " },
  { duration: 1486, line: "Anyway", sameLine: true },
  { asciiArt: 1, duration: 1765, line: ", this cake is great." },
  { duration: 1904, line: "It's so delicious and moist." },
  { duration: 418, line: " " },
  { asciiArt: 11, duration: 1927, line: "Look at me still talking" },
  { asciiArt: 5, duration: 2090, line: "when there's Science to do." },
  { asciiArt: 0, duration: 1695, line: "When I look out there," },
  { duration: 2183, line: "it makes me GLaD I'm not you." },
  { asciiArt: 4, duration: 2043, line: "I've experiments to run." },
  { asciiArt: 2, duration: 2020, line: "There is research to be done." },
  { asciiArt: 0, duration: 1625, line: "On the people who are" },
  { duration: 348, line: "still ", sameLine: true },
  { duration: 1440, line: "alive." },
  { duration: 200, line: " " },
  { duration: 10, line: "&" },
  { duration: 100, line: "&" },
  { duration: 10, line: "^" },
  { duration: 10, line: "^" },
  { duration: 10, line: "^" },
  { duration: 300, line: "PS: ", sameLine: true },
  { duration: 1625, line: "And believe me I am" },
  { duration: 1138, line: "still alive." },
  { duration: 800, line: " " },
  { duration: 198, line: "PPS: ", sameLine: true },
  { duration: 1904, line: "I'm doing Science and I'm" },
  { duration: 1091, line: "still alive." },
  { duration: 800, line: " " },
  { duration: 175, line: "PPPS: ", sameLine: true },
  { duration: 1904, line: "I feel FANTASTIC and I'm" },
  { duration: 1091, line: "still alive." },
  { duration: 100, line: "^" },
  { duration: 1154, line: "FINAL THOUGHT: " },
  { duration: 1579, line: "While you're dying I'll be" },
  { duration: 1254, line: "still alive." },
  { duration: 100, line: "^" },
  { duration: 829, line: "FINAL THOUGHT PS: " },
  { duration: 1834, line: "And when you're dead I will be" },
  { duration: 1161, line: "still alive." },
  { duration: 459, line: "^" },
  { duration: 400, line: "^" },
  { duration: 1184, line: "STILL ALIVE" },
  { duration: 200, line: " " },
  { duration: 100, line: "&" },
  { duration: 45279, line: " " },
  { duration: 279, line: " " },
];
